# Generated by Django 5.2 on 2025-05-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Ads',
        ),
    ]
