# Generated by Django 5.2 on 2025-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ads_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='image',
        ),
        migrations.AddField(
            model_name='ads',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фото'),
        ),
    ]
