# Generated by Django 5.2 on 2025-05-08 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_ads_image_ads_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='condition',
            field=models.CharField(choices=[('used', 'Б/У'), ('new', 'Новое')], max_length=20, verbose_name='Состояние'),
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=20, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('accepted', 'Приняли'), ('rejected', 'Отклонили')], default='waiting', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата Обновления')),
                ('ad_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_receivers', to='ads.ads', verbose_name='Объявление получателя')),
                ('ad_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_senders', to='ads.ads', verbose_name='Объявление отправителя')),
            ],
        ),
    ]
