# Generated by Django 5.2 on 2025-05-09 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ads_condition_exchangeproposal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeproposal',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_exchange_proposals', to='ads.ads', verbose_name='Объявление получателя'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_exchange_proposals', to='ads.ads', verbose_name='Объявление отправителя'),
        ),
    ]
