# Generated by Django 5.2 on 2025-05-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_exchangeproposal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='condition',
            field=models.CharField(choices=[('used', 'Б/У'), ('new', 'Новое')], max_length=50, verbose_name='Состояние'),
        ),
    ]
