# Generated by Django 5.2 on 2025-05-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_ads_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Комментарий'),
        ),
    ]
